# Generated by Django 5.2.7 on 2025-10-07 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField()),
                ('nome_responsavel', models.CharField(blank=True, max_length=150, null=True)),
                ('contato_responsavel', models.CharField(blank=True, max_length=50, null=True)),
                ('mensalidade', models.DecimalField(decimal_places=2, default=40.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('OUTRO', 'Outro')], max_length=20, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='escolinha.aluno')),
            ],
            options={
                'ordering': ['-data_vencimento', 'aluno'],
                'indexes': [models.Index(fields=['data_vencimento'], name='escolinha_p_data_ve_948cfe_idx')],
            },
        ),
    ]
