# Generated by Django 5.2.7 on 2025-10-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolinha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('OUTRO', 'Outro')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
