# Generated by Django 5.2.7 on 2026-01-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolinha', '0002_alter_pagamento_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('OUTRO', 'Outro')], default='PIX', max_length=20),
        ),
    ]
