# Generated by Django 5.2.7 on 2026-01-14 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolinha', '0004_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='escolinha.turma'),
            preserve_default=False,
        ),
    ]
