# Generated by Django 5.2.7 on 2026-01-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolinha', '0005_aluno_turma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['nome'], 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['is_active', 'nome_completo'], name='escolinha_a_is_acti_ee4c91_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['turma', 'is_active'], name='escolinha_a_turma_i_f6ce1a_idx'),
        ),
    ]
